### ISSUE TITLE
No year on audio export

### ISSUE THREAD

**Issue by relenteny** [ukdtom/ExportTools.bundle#115]
First off, great tool! I have exported movies, TV shows and audio successfully. The only issue I'm having is that the audio export has N/A for all values in the year column. The export documentation states that this works for "Premium Library Only." I guess I don't understand what that means. I have a premium subscription. Is it something else? In the Plex UI, when I look at my audio, I do see the year displayed.

**Comment by ukdtom** [comment]
Heh, and guess the Wiki is outdated on that....
Plex used to have what was known as Premium Libraries for Audio, where the year was stored with the track itself.

This is no longer the case, and Year is now only stored on the Album record
This sadly would req. two calls for every record, in order to look up that info, and as such, currently isn't supported....

I did however flag this as an enhancement, but no ETA

**Comment by relenteny** [comment]
Ah. Thanks for the info and tracking it as an enhancement!

**Comment by ukdtom** [comment]
Irrelevant, due to
[WebTools-NG](https://forums.plex.tv/t/webtools-ng/598539)
