### ISSUE TITLE
Supply option to export duplicate movies on separate lines

### ISSUE THREAD

**Issue by nosmokingbandit** [ukdtom/ExportTools.bundle#27]
As it is, duplicate copies of a movie are exported on a single line, with fields such as 'Part Size as Bytes' expressed as '12345 - 6789'.

This makes parsing the output very difficult.

Can an option be added to require that each entry has it's own specific line?

**Comment by rossinior** [comment]
Like that possible enhancement

**Comment by arsaboo** [comment]
Anxiously waiting for this....thanks!

**Comment by ukdtom** [comment]
Sadly, it turned out to be too huge a change, since i was the core of the engine :(

And beside adding new fields, all other dev works for this plugin has stopped, due to the Up-Hill work after: https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/

But when said, who knows what will happen in the future ;)
