### ISSUE TITLE
Export Live TV channels to m3u8/cvs

### ISSUE THREAD

**Issue by mattgorski** [ukdtom/ExportTools.bundle#48]
I am trying to develop a Live Channels plugin for Android TV to watch live tv and set recordings through plex backend using Live Channels frontend (plex epg guide isn't the greatest imo).

Question is can we somehow create a live_tv export to export all epg data into xmltv.xml and channels.m3u8?

**Comment by ukdtom** [comment]
This would be very hard work to get this done....
And fail to see a more general use case for this, so unless you come up with some very good arguments, I would refrain from making it.

But you could browse `PMS:32400/media/providers` yourself, and work your way down from there

**Comment by mattgorski** [comment]
Appreciate the response.  The conversion process alone (to xmltv) I know would be difficult to export.  I will dig through my plex and see what I can gather for Live TV and EPG data.

I have opened my massive epg db file in an sql browser and thats where im starting:
$PLEXHOME/PlexFiles/Plug-in Support/Databases/tv.plex.providers.epg.onconnect

**Comment by ukdtom** [comment]
I would NOT go down that road, since messing with the database directly is NOT supported on all platforms....

I would 4 sure use the web API, as I suggested, and is also what I use for ExportTools myself, in order to make sure it works on all PMS platforms.

And closing this one for now....

Do reopen if needed
